#!/bin/sh

set -e

green="\033[32m"
red="\033[31m"
color_reset="\033[0m"

function success() {
  echo "${green}${1}${color_reset}"
  exit 0
}

function failure() {
  echo "${red}${1}${color_reset}"
  exit 1
}

if [ ! -d .git ]; then
  failure "You must run this command from inside a git repository"
fi

local_branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)

tracking_remote=$(git config branch.${local_branch}.remote)
: ${tracking_remote:="origin"}

git fetch "$tracking_remote"

tracking_branch=$(git config branch.${local_branch}.merge | sed 's|refs/heads/||')
: ${tracking_branch:=$local_branch}

upstream_branch="${tracking_remote}/${tracking_branch}"

if ! git rev-parse "$upstream_branch" > /dev/null; then
  failure "Upstream branch ${upstream_branch} doesn't exist!"
fi

head_sha=$(git rev-parse HEAD)
remote_sha=$(git rev-parse "$upstream_branch")

if [ "$head_sha" = "$remote_sha" ]; then
  echo "Neither your local branch '$local_branch', nor the remote branch '$upstream_branch' have moved on."
  success "Already up to date!"
fi

merge_base_sha=$(git merge-base "$head_sha" "$remote_sha")

if [ "$merge_base_sha" = "$remote_sha" ]; then
  echo "Remote branch $upstream_branch has not moved on"
  success "Already up to date!"
fi

stashed_changes=false

if git status --short | egrep 'M|A|D|UU'; then
  echo "Stashing local changes"
  git stash
  stashed_changes=true
fi

if [ "$merge_base_sha" = "$head_sha" ]; then
  echo "Local branch '$local_branch' has not moved on. Fast-forwarding..."
  git merge --ff-only "$upstream_branch"
else
  echo "Both local and remote branches have moved on. Branch '$local_branch' needs to be rebased onto '$upstream_branch'"
  git rebase --preserve-merges "$upstream_branch"
fi

if $stashed_changes; then
  echo "Reapplying local changes"
  git stash pop
fi

default_format="%C(yellow)%h%Cblue%d%Creset %s - %C(white)%an %Cgreen(%cr)%Creset"

if git config pretty.custom; then
  default_format="custom"
fi

git log --format="$default_format" --graph "$merge_base_sha".."$remote_sha"

success "All good"
